apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kargo-ssh
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    stage: dev
